---
title: Syllabus
author: 
output: pdf_document
---


## Teaching team and office hours

|  Role        | Name       | Office Hours         | Location              |
|----------|-----------|---------------|-----------------------|
| Instructor | Professor Rebecca Steorts  | MW 1:00 pm -- 2:00 PM |    Old Chem 216         |
| Teaching Assistant   |  Suchismita  Roy   |   TuTh   4:00 -- 5:00 PM             |            Zoom        |
| Teaching Assistant   |  Wenxin Guo        |    MW 4:30 -- 5:30 PM               |           Zoom         |

## Course info

|          | Day       | Time          | Location              |
|----------|-----------|---------------|-----------------------|
| Lectures | Mon & Wed | 11:45 am - 1:00 pm | Gray 228         |
| Lab   | Friday    | 11:45 am - 1:00 pm | Social Sciences 105       |

## Zoom Information

We will utilize the following zoom link for unscheduled office hours, zoom office hours, or other emergent issues as needed regarding any classes. Zoom Meeting ID: 979 2535 4560. The passcode will be posted on canvas for security reasons. 

## Textbooks

All books are freely available online. Print copies are also available for purchase.

|                                                                                      |                                      |                              |
|--------------------------------------------------------------------------------------|--------------------------------------|------------------------------|
| [Beyond Multiple Linear Regression](https://bookdown.org/roback/bookdown-BeyondMLR/) | Roback, Legler                       | CRC Press, 1st edition, 2020 |
| [R for Data Science](https://r4ds.hadley.nz/)                                        | Wickham, Cetinkaya-Rundel, Grolemund | O'Reilly, 2nd edition, 2023  |
| [Tidy Modeling with R](https://www.tmwr.org/iterative-search)                        | Kuhn, Silge                          | O'Reilly, 1st edition, 2022  |

## Course description

STA 310 builds upon the content in STA 210: Regression Analysis. In 310, we will review aspects of prior material that will be utilized in the course relevant to generalized linear models (GLMs), a broad modeling framework that includes linear and logistic models, among others. Such review areas will be on distributions, regression analysis, and likelihoods, which are useful techniques in all areas of statistical analysis. Students will learn the basic theory and applications of GLMs and how they can used to model a variety of response variables with non-normal distributions. Students will also learn an extension of GLMs that can be applied to modeling data with correlated observations. 

## **Prerequisites**

The prerequisites for the course are STA 210 and one of STA 230/STA 231/STA 240. This course assumes students have some familiarity with linear regression, analyzing data using RStudio, using version control with Git and collaborating using GitHub. The semester will start with a review of topics that will be extremely revelant to the course material, such as distributions, regression analysis, and likelihoods, among a few other topics. 

## Course learning objectives

By the end of the semester, you will be able to ...

-   describe generalized linear models (GLMs) as a unified framework.
-   explain how specific models fit into the GLM framework.
-   identify the appropriate model given the data and analysis objective.
-   analyze real-world data by fitting and interpreting GLMs.
-   use R for analysis for reproducible analysis and synthesize reports on your own.
-   effectively communicate results from statistical analyses to a general audience via writing. 

## Course community

### Duke Community Standard

As a student in this course, you have agreed to uphold the [Duke Community Standard](https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard) as well as the practices specific to this course.

<iframe width="560" height="315" src="https://www.youtube.com/embed/_KN97j30ST4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

### Inclusive community

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength, and benefit. It is my intent to present materials and activities that are respectful of diversity and in alignment with [Duke's Commitment to Diversity and Inclusion](https://provost.duke.edu/initiatives/commitment-to-diversity-and-inclusion). Your suggestions are encouraged and appreciated. Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

Furthermore, I would like to create a learning environment that supports a diversity of thoughts, perspectives and experiences, and honors your identities. To help accomplish this:

-   If you have a name that differs from those that appear in your official Duke records, please let me know! 
-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. If you prefer to speak with someone outside of the course, your academic dean is an excellent resource.
-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please let me or a member of the teaching team know.

### Accessibility

If there is any portion of the course that is not accessible to you due to challenges with technology or the course format, please let me know so we can make appropriate accommodations.

The [Student Disability Access Office (SDAO)](https://access.duke.edu/students) is available to ensure that students are able to engage with their courses and related assignments. Students should be in touch with the Student Disability Access Office to [request or update accommodations](https://access.duke.edu/requests) under these circumstances.

### Communication

All lecture notes, assignment instructions, an up-to-date schedule, and other course materials may be found on the course website, [https://github.com/resteorts/generalized-linear-models](https://github.com/resteorts/generalized-linear-models)

Announcements will be sent through Canvas and email. Please check your email regularly to ensure you have the latest announcements for the course. Most course announcements will be made in class, so please be sure to stay up to date with these if you do miss class as I will not re-post these items. 

### Where to get help

-   If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.
-   The teaching team is here to help you be successful in the course. You are encouraged to attend office hours[^1] to ask questions about the course content and assignments. Many questions are most effectively answered as you discuss them with others, so office hours are a valuable resource. Please use them!
-   Outside of class and office hours, any general questions about course content or assignments should be posted on Duke Ed. There is a chance another student has already asked a similar question, so please check the other posts before adding a new question. If you know the answer to a question posted on the message board, I encourage you to respond!

[^1]: Office hours are times the teaching team set aside each week to meet with students. [Click here](https://academicguides.duke.edu/reasons-to-attend-office-hours/) to learn more about how to effectively use office hours.

Check out the [Support](support.qmd) page for more resources.

### Email

If there is a question that's not appropriate for Ed Discussion (or you may be unsure about), please email directly with "STA 310" in the subject line. Barring extenuating circumstances, I will respond to STA 310 emails as quickly as possible. Response time may be slower for emails received Friday - Sunday.

## Activities & Assessment

The activities and assessments in this course are designed to help you successfully achieve the course learning objectives. Each activity and assessment is part of the *prepare, practice, perform* cycle for each topic.

-   **Prepare**: Includes reading assignments and occasional videos to introduce new concepts and ensure a basic comprehension of the material.

-   **Practice**: Includes in-class activities and application exercises to explore the topics new topics in more depth. These activities will be completed during lecture. As they are intended for practice, they will not be graded.

-   **Perform**: Includes homework, quizzes, and the projects. These assignments are an opportunity for you to demonstrate your understanding of the course material and how it is applied to the analysis of real-world data.

### Readings

There will be reading assignments to accompany each topic. Readings will primarily come from the course textbook [*Beyond Multiple Linear Regression*](https://bookdown.org/roback/bookdown-BeyondMLR/), but they may periodically include articles and other resources. It is strongly recommended that you complete the readings before lectures, so you have an introduction to the topic before class.

### Lectures

Lectures will be interactive with a mix of presenting lecture notes, short in-class activities, and application exercises. The activities and application exercises will give you an opportunity to explore concepts in more depth and get practice applying them to real-world data.

### Homework

There will be a series of homework assignments during the semester. In these assignments, you will apply what you've learned as you answer conceptual questions and complete guided and open-ended analyses. You may discuss homework assignments with other students; however, homework should be completed and submitted individually. Homework will be submitted to both Gradescope and Canvas.

*The lowest homework grade is dropped.*

### Quizzes

There will be 4-6 quizzes during the semester. Quizzes will cover the readings, lecture notes and activities, and any assignments since the previous quiz. 

*The lowest quiz grade is dropped.*

## Grading

The final course grade will be calculated as follows:

<center>

| Category      | Percentage |
|---------------|------------|
| Homework      | 40%        |
| Quizzes       | 60%        |

</center>

<br>

The final letter grade will be determined based on the following thresholds:

<center>

| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |

These are upper bounds for grade cutoffs, depending on the class performance the cutoffs may be lowered but they won't be increased.

## Course policies

### Academic honesty

By participating in this course, you agree to abide by the following when completing assignments:

-   The homework assignments must be completed individually and you are welcomed to discuss the assignment with classmates at a high level (e.g., discuss what's the best way for approaching a problem, what functions are useful for accomplishing a particular task, etc.). However you may not directly share answers to homework questions (including any code) with anyone other than myself and the teaching assistants.

-   You may not discuss or otherwise work with others on quizzes. Unauthorized collaboration or using unauthorized materials will be considered a violation for all students involved.

-   **Reusing code**: Unless explicitly stated otherwise, you may make use of online resources (e.g. StackOverflow) for coding examples on assignments. If you directly use code from an outside source (or use it as inspiration), you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

-   **Use of artificial intelligence (AI)**: You should treat AI tools, such as ChatGPT, the same as other online resources. There are two guiding principles that govern how you can use AI in this course:^[2](https://sta210-fa23.netlify.app/syllabus#fn2)^ (1) *Cognitive dimension:* Working with AI should not reduce your ability to think clearly. We will practice using AI to facilitate---rather than hinder---learning. (2) *Ethical dimension***:** Students using AI should be transparent about their use and make sure it aligns with academic integrity.

    -   **AI tools for code:** You may make use of the technology for coding examples on assignments; if you do so, you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. You may use [these guidelines](https://guides.lib.monash.edu/c.php?g=219786&p=6972087) for citing AI-generated content.

    -   **No AI tools for narrative:** Unless instructed otherwise, AI is [**not**]{.underline} permitted for writing narrative on assignments. In general, you may use AI as a resource as you complete assignments but not to answer the exercises for you. You are ultimately responsible for the work you turn in; it should reflect your understanding of the course content.

If you are unsure if the use of a particular resource complies with the academic honesty policy, please ask me or a teaching assistant.

Regardless of course delivery format, it is the responsibility of all students to understand and follow all Duke policies, including academic integrity (e.g., completing one's own work, following proper citation of sources, adhering to guidance around group work projects,and more). Ignoring these requirements is a violation of the Duke Community Standard. Any questions and/or concerns regarding academic integrity can be directed to the Office of Student Conduct and Community Standards at [conduct\@duke.edu](mailto:conduct@duke.edu).

Any violations in academic honesty standards as outlined in the [Duke Community Standard](https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard) and those specific to this course will automatically result in a 0 for the assignment and will be reported to the [Office of Student Conduct](https://studentaffairs.duke.edu/conduct) for further action.

### Late work & extensions

Given that things come up periodically, we are dropping your lowest homework and quizzes. Given this, there will be no late extensions on any assignments. Please make sure that you stay up to date on the class and assignments. 
The due dates for assignments are there to help you keep up with the course material and to ensure the teaching team can provide feedback within a timely manner. 


If there are circumstances that are having a longer-term impact on your academic performance, please let your academic dean know, as they can be a resource. Please let me know if you need help contacting your academic dean.

### Regrade requests

Regrade requests must be submitted via Gradescope within one week of the assignment. Regrade requests will 
only be considered if points were tallied incorrectly or a correct answer was mistakenly marked as incorrect. Requests to dispute the number of points deducted for an incorrect response will not be considered. If a regrade request is submitted, the entire question will be regraded, so your score could increase, decrease, or remain unchanged.

### Attendance

You are expected to attend all lectures and labs with a fully-charged laptop or tablet with access to RStudio. We understand there may be times when you are unable to attend a class meeting; in such instances it is your responsibility to make up the missed material. Labs will primarily be used to work on homework assignments or clarify questions from lecture. If you miss a lab meeting dedicated to homework or a review session, it is your responsibility to catch up on this information. [Click here](https://trinity.duke.edu/undergraduate/academic-policies/class-attendance-and-missed-work) for more information on the Trinity attendance policies.

### Attendance Policy Related to COVID Symptoms, Exposure, or Infection

Student health, safety, and well-being are the university's top priorities. To help ensure your well-being and the well-being of those around you, please do not come to class if you have tested positive for COVID-19 or have possible symptoms and have not yet been tested. If any of these situations apply to you, you must follow university guidance related to the ongoing COVID-19 pandemic and current health and safety protocols. If you are experiencing any COVID-19 symptoms, contact student health ([dshcheckin\@duke.edu](mailto:dshcheckin@duke.edu), 919-681-9355). Learn more about current university policy related to COVID-19 at [coronavirus.duke.edu](https://coronavirus.duke.edu/).

To keep the university community as safe and healthy as possible, you will be expected to follow these guidelines. Please reach out to me and your academic dean as soon as possible if you need to quarantine or isolate so that we can discuss arrangements for your continued participation in class.

## Accommodations

### **Academic accommodations**

If you are a student with a disability and need accommodations for this class, it is your responsibility to register with the Student Disability Access Office (SDAO) and provide them with documentation of your disability. SDAO will work with you to determine what accommodations are appropriate for your situation. Please note that accommodations are not retroactive and disability accommodations cannot be provided until a Faculty Accommodation Letter has been given to me. Please contact SDAO for more information: [sdao\@duke.edu](mailto:sdao@duke.edu) or [access.duke.edu](https://access.duke.edu/).

### **Religious accommodations**

Students are permitted by university policy to be absent from class to observe a religious holiday. Accordingly, Trinity College of Arts & Sciences and the Pratt School of Engineering have established procedures to be followed by students for notifying their instructors of an absence necessitated by the observance of a religious holiday. Please submit requests for religious accommodations at the beginning of the semester so that we can work to make suitable arrangements well ahead of time. You can find the policy and relevant notification form here: [trinity.duke.edu/undergraduate/academic-policies/religious-holidays](https://trinity.duke.edu/undergraduate/academic-policies/religious-holidays)

## Additional support

### Academic Resource Center

The Academic Resource Center (the ARC) offers services to support students academically during their undergraduate careers at Duke. The ARC can provide support with time management, academic skills and strategies, unique learning styles, peer tutoring, learning consultations, learning communities, and more. ARC services are available free to any Duke undergraduate student, in any year, studying in any discipline.

Contact <a href="mailto:arc@duke.edu" title="email">ARC\@duke.edu</a>, 919-684-5917.

### Mental health and wellness resources

Student mental health and wellness is of primary importance at Duke, and the university offers resources to support students in managing daily stress and self-care. Duke offers several resources for students to seek assistance on coursework and to nurture daily habits that support overall well-being, some of which are listed below

-   **DuWell**: (919) 681-8421, provides Moments of Mindfulness (stress management and resilience building) and Koru (meditation) programming to assist students in developing a daily emotional well-being practice. [Click here](https://studentaffairs.duke.edu/duwell) to see schedules for programs please see. All are welcome and no experience necessary. [duwell\@studentaffairs.duke.edu](mailto:duwell@studentaffairs.duke.edu), or [studentaffairs.duke.edu/duwell](https://studentaffairs.duke.edu/duwell)

If your mental health concerns and/or stressful events negatively affect your daily emotional state, academic performance, or ability to participate in your daily activities, many resources are available to help you through difficult times. Duke encourages all students to access these resources.

-   **DukeReach**: Provides comprehensive outreach services to identify and support students in managing all aspects of well-being. If you have concerns about a student's behavior or health visit the website for resources and assistance. [studentaffairs.duke.edu/dukereach](http://studentaffairs.duke.edu/dukereach)
-   **Counseling and Psychological Services (CAPS)**: CAPS services include individual, group, and couples counseling services, health coaching, psychiatric services, and workshops and discussions. CAPS also provides referral to off-campus resources for specialized care. (919) 660-1000. [studentaffairs.duke.edu/caps](https://studentaffairs.duke.edu/caps)
-   **Blue Devils Care**: A convenient, confidential, and free way for Duke students to receive 24/7 mental health support through TalkNow and scheduled counseling. [bluedevilscare.duke.edu](https://bluedevilscare.duke.edu)
-   **Two-Click Support**: Duke Student Government and DukeReach partnership that connects students to help in just two clicks. [bit.ly/TwoClickSupport](https://bit.ly/TwoClickSupport)

### Technology Accommodations

Students with demonstrated high financial need who have limited access to computers may request assistance in the form of loaner laptops. For new Spring 2024 technology assistance requests, please go [here](https://dukelife.duke.edu/technology-assistance-program/). Please note that supplies are limited.




